name: Deploy to GitHub Pages and OSS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ENDPOINT_URL: ${{ secrets.AWS_ENDPOINT_URL }}
      AWS_S3_USE_PATH_STYLE: true
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ''

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Build
        run: sh build.sh

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src/public
          publish_branch: pages
          force_orphan: true

      # 部署到 OSS (移除了 configure-aws-credentials Action)
      - name: Empty S3 bucket
        run: |
          aws s3 rm s3://${{ secrets.S3_BUCKET }}/ --recursive \
          --endpoint-url $AWS_ENDPOINT_URL

      - name: Upload files to S3
        run: |
          aws s3 cp ./src/public/ s3://${{ secrets.S3_BUCKET }}/ --recursive \
          --endpoint-url $AWS_ENDPOINT_URL
